name: Build XeLaTeX Resume

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install XeLaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-xetex \
          texlive-fonts-recommended \
          texlive-latex-extra \
          fonts-freefont-otf

    - name: Compile with XeLaTeX
      run: |
        xelatex -interaction=nonstopmode -halt-on-error resume.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: willBonilla_Resume.pdf
