name: Build LaTeX Resume

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v2

    - name: Install LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error your_resume.tex

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: resume-pdf
        path: resume_Will_Bonilla.pdf
